development:
    paypal_email: weihsi.hu-facilitator@logical-thinking.co.uk
    paypal_secret: whoway
    paypal_cert_id: B2KWKJEXPLK3S
    paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
    paypal_email: test@example.com
    paypal_secret: testsecret
    paypal_cert_id: X123456789
    paypal_url: testpaypalurl

production:
    paypal_email: weihsi.hu@logical-thinking.co.uk
    paypal_secret: reallysecretpassword
    paypal_cert_id: B2KWKJEXPLK3S
    paypal_url: https://www.paypal.com/cgi-bin/webscr
